name: Harvester STIG Configuration
stages:
    initramfs:
        - commands:
            - groupadd etcd
            - useradd -r -c "etcd user" -G etcd -s /sbin/nologin -M etcd
            - sysctl -p
          files:
            - path: /etc/sysctl.d/99-sysctl.conf
              permissions: 600
              owner: 0
              group: 0
              content: |
                vm.panic_on_oom=0
                vm.overcommit_memory=1
                kernel.panic=10
                kernel.panic_on_oops=1
            - path: /etc/rancher/rke2/config.yaml.d/51-rke2-pss-custom.yaml
              permissions: 600
              owner: 0
              group: 0
              content: |
                apiVersion: apiserver.config.k8s.io/v1
                kind: AdmissionConfiguration
                plugins:
                  - name: PodSecurity
                    configuration:
                      apiVersion: pod-security.admission.config.k8s.io/v1
                      kind: PodSecurityConfiguration
                      defaults:
                        enforce: "baseline"
                        enforce-version: "latest"
                        audit: "baseline"
                        audit-version: "latest"
                        warn: "baseline"
                        warn-version: "latest"
                      exemptions:
                        usernames: []
                        runtimeClasses: []
                        namespaces: [calico-apiserver,
                                    calico-system,
                                    cattle-alerting,
                                    cattle-csp-adapter-system,
                                    cattle-elemental-system,
                                    cattle-epinio-system,
                                    cattle-externalip-system,
                                    cattle-fleet-local-system,
                                    cattle-fleet-system,
                                    cattle-gatekeeper-system,
                                    cattle-global-data,
                                    cattle-global-nt,
                                    cattle-impersonation-system,
                                    cattle-istio,
                                    cattle-istio-system,
                                    cattle-logging,
                                    cattle-logging-system,
                                    cattle-monitoring-system,
                                    cattle-neuvector-system,
                                    cattle-prometheus,
                                    cattle-provisioning-capi-system,
                                    cattle-resources-system,
                                    cattle-sriov-system,
                                    cattle-system,
                                    cattle-ui-plugin-system,
                                    cattle-windows-gmsa-system,
                                    cert-manager,
                                    cis-operator-system,
                                    fleet-default,
                                    harvester-system,
                                    harvester-public,
                                    ingress-nginx,
                                    istio-system,
                                    kube-node-lease,
                                    kube-public,
                                    kube-system,
                                    longhorn-system,
                                    rancher-alerting-drivers,
                                    security-scan,
                                    tigera-operator]
