{{ if .ServerURL -}}
server: {{ .ServerURL }}
{{ if or (eq .Role "management") (eq .Role "witness") }}
role: server
{{- else -}}
role: agent
{{ end }}
{{- else -}}
role: cluster-init
{{ end }}
token: {{ printf "%q" .Token }}
kubernetesVersion: {{ .RuntimeVersion }}
rancherVersion: {{ .RancherVersion }}
rancherInstallerImage: rancher/system-agent-installer-rancher:{{ .RancherVersion }}
