resources:
- apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    name: rancher-monitoring-crd
    namespace: fleet-local
  spec:
    chart: rancher-monitoring-crd
    version: {{ .MonitoringChartVersion }}
    targetNamespace: cattle-monitoring-system
    repo: http://harvester-cluster-repo.cattle-system.svc/charts
