resources:
- apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    name: rancher-logging-crd
    namespace: fleet-local
  spec:
    chart: rancher-logging-crd
    version: {{ .LoggingChartVersion }}
    targetNamespace: cattle-logging-system
    repo: http://harvester-cluster-repo.cattle-system.svc/charts
