cni: multus,canal
cluster-cidr: 10.52.0.0/16
service-cidr: 10.53.0.0/16
cluster-dns: 10.53.0.10
tls-san:
  - {{ .Vip }}
{{- with $args :=  .GetKubeletArgs }}
kubelet-arg:
{{- range $arg := $args }}
- {{ printf "%q" $arg }}
{{- end }}
{{- end }}
audit-policy-file: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml
# Disable snapshot-controller related charts because we manage them in Harvester.
# RKE2 enables these charts by default after v1.25.7 (https://github.com/rancher/rke2/releases/tag/v1.25.7%2Brke2r1)
disable:
- rke2-snapshot-controller
- rke2-snapshot-controller-crd
- rke2-snapshot-validation-webhook
node-label:
- harvesterhci.io/managed=true
{{ if eq .Role "witness" }}
disable-apiserver: true
disable-controller-manager: true
disable-scheduler: true
{{ end }}
